// flow-typed signature: b23772b00f0e652fe01bd91b89f5238e
// flow-typed version: <<STUB>>/init_v^0.1.2/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'init'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'init' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'init/init' {
  declare module.exports: any;
}

// Filename aliases
declare module 'init/init.js' {
  declare module.exports: $Exports<'init/init'>;
}
