const ADD_SUCCESS = 'note/ADD_SUCCESS';
const DELETE_SUCCESS = 'note/DELETE_SUCCESS';
const TOGGLE_COMPLETED_SUCCESS = 'note/TOGGLE_COMPLETED_SUCCESS';
const CHANGE_FILTER = 'note/CHANGE_FILTER';

const FETCH_REQUEST = 'note/FETCH_REQUEST';
const FETCH_SUCCESS = 'note/FETCH_SUCCESS';
const FETCH_FAILED = 'note/FETCH_FAILED';

export default {
  ADD_SUCCESS,
  DELETE_SUCCESS,
  TOGGLE_COMPLETED_SUCCESS,
  CHANGE_FILTER,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_FAILED
};
